
name: sunilkaworkflow
on:
  push:
    branches:
      - 'main'
      - 'feature/**'
jobs:
  my-forst-workflow:
    name: sunilkifirstjob 
    runs-on: suniselfhost
    steps:
      - name: Print some words about India
        run: echo " India is great"
