name: Terraform Deploy

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  terraform:
    name: Terraform Apply
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./  # repo root, kyunki modules ../rg, ../sa, ../sc main ke bahar hain

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_IN_AUTOMATION: 1
          TF_INPUT: false

      - name: Terraform Plan
        run: terraform plan -var rg_name="anoop_rg" -var location="eastus" -var sa_name="anoopkastorageacc" -var container_name="tfstate" -input=false
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_IN_AUTOMATION: 1
          TF_INPUT: false

      - name: Terraform Apply
        run: terraform apply -auto-approve -var rg_name="anoop_rg" -var location="eastus" -var sa_name="anoopkastorageacc" -var container_name="tfstate" -input=false
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_IN_AUTOMATION: 1
          TF_INPUT: false
